export const AppConfig = {
  ROSBRIDGE_SERVER_IP: "192.168.0.100",
  ROSBRIDGE_SERVER_PORT: "9090",
  CAMERA_PORT: "8080",
  RECONNECTION_TIME: 1000,

  CMD_VEL_TOPIC: "/cmd_vel",
  ROBOT_POSE_TOPIC: "/odom",
  ROBOT_VELOCITY_TOPIC: "/odom",
  MAP_TOPIC: "/ui/map",
  GLOBAL_COSTMAP_TOPIC: "/global_costmap/costmap",
  LOCAL_COSTMAP_TOPIC: "/local_costmap/costmap",
  SCAN_TOPIC: "/scan_filtered",
  PLAN_TOPIC: "/plan",
  TF_TOPIC: "/tf",
  TF_STATIC_TOPIC: "/tf_static",
  AMCL_POSE_TOPIC: "/ui/amcl_pose",
  NAV_STATUS_TOPIC: "/ui/navigate_to_pose/status",
  NAV_FEEDBACK_TOPIC: "/navigate_to_pose/_action/feedback",
  DOCK_STATUS_TOPIC: "/ui/dock_robot/status",
  DOCK_TRIGGER_STATUS_TOPIC: "/dock_trigger_status",
  UNDOCK_STATUS_TOPIC: "/ui/undock_robot/status",
  GOAL_POSE_TOPIC: "/goal_pose",
  INITIAL_POSE_TOPIC: "/initialpose",
  UI_OPERATION_TOPIC: "/ui_operation",
  UI_MESSAGE_TOPIC: "/ui_message",
  UI_OPERATION: "/ui_operation",
  SET_POINT: "/may_set_point",
  WP_REQ: "/WP_req",
  SENSORS_TOPIC: "/sensors",
  BATTERY_TOPIC: "/battery_status",
  CHARGE_STATION_CONNECTED: "/charge_station_connected",

  MAX_LINEAR_SPEED: 0.2,
  MAX_ANGULAR_SPEED: 2,
};
