#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ASSET_DIR="${REPO_ROOT}/docs/assets"
SOURCE_VIDEO="${1:-${ASSET_DIR}/openamrobot_ui_feature_tour.mp4}"
OUTPUT_VIDEO="${2:-${ASSET_DIR}/openamrobot_ui_feature_tour_with_audio.mp4}"
OUTPUT_AUDIO="${3:-${ASSET_DIR}/openamrobot_ui_feature_tour_narration.m4a}"
ESPEAK_BIN="${ESPEAK_BIN:-$(command -v espeak-ng || true)}"

for command_name in ffmpeg ffprobe; do
  if ! command -v "${command_name}" >/dev/null 2>&1; then
    echo "ERROR: ${command_name} is required."
    exit 1
  fi
done

if [ -z "${ESPEAK_BIN}" ] || [ ! -x "${ESPEAK_BIN}" ]; then
  echo "ERROR: espeak-ng is required to generate the narration."
  echo "Install it with: sudo apt install espeak-ng"
  exit 1
fi

if [ ! -f "${SOURCE_VIDEO}" ]; then
  echo "ERROR: source video not found: ${SOURCE_VIDEO}"
  echo "Create it first with: bash scripts/create_asset_video.sh"
  exit 1
fi

SEGMENT_DURATIONS=(
  4
  3.5 3.5 3.5 3.5
  3.5 3.5 3.5 3.5
  3.5 3.5 3.5 3.5
  3.5 3.5 3.5 3.5
  4
)

NARRATIONS=(
  "Open A M Robot U I. One dashboard for your R O S two robot."
  "View the map, drive manually, send goals, and dock."
  "Build and edit reusable waypoint routes for each map."
  "Create, switch, rename, and manage robot maps."
  "Build validated robot routines visually with Blockly."
  "Schedule routine browser-side actions for selected times."
  "Build missions with waypoints, waits, and docking."
  "Monitor the camera, battery, motion, and status."
  "Explore the robot model, joints, and live overlays."
  "Register external hardware and network devices."
  "Check readiness, battery, devices, and faults."
  "Track distance, uptime, navigation, and docking."
  "Record and replay R O S bags for debugging."
  "Review navigation, battery, and safety events."
  "Inspect logs and live topics in the browser."
  "Update selected Nav two runtime parameters."
  "Choose which robot profile this browser controls."
  "Explore safely in Demo Mode, then self-host when you are ready."
)

AUDIO_TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${AUDIO_TMP_DIR}"' EXIT
CONCAT_LIST="${AUDIO_TMP_DIR}/segments.txt"
: >"${CONCAT_LIST}"

for index in "${!NARRATIONS[@]}"; do
  raw_audio="$(printf "%s/raw-%02d.wav" "${AUDIO_TMP_DIR}" "${index}")"
  segment_audio="$(printf "%s/segment-%02d.wav" "${AUDIO_TMP_DIR}" "${index}")"
  duration="${SEGMENT_DURATIONS[${index}]}"

  "${ESPEAK_BIN}" \
    -v en-us -s 190 -p 45 -a 150 \
    -w "${raw_audio}" "${NARRATIONS[${index}]}"

  speech_duration="$(
    ffprobe -v error -show_entries format=duration -of csv=p=0 "${raw_audio}"
  )"
  if ! awk -v speech="${speech_duration}" -v segment="${duration}" \
    'BEGIN { exit !(speech + 0.15 <= segment) }'; then
    echo "ERROR: narration segment ${index} is too long (${speech_duration}s for ${duration}s)."
    exit 1
  fi

  ffmpeg -hide_banner -loglevel error \
    -i "${raw_audio}" \
    -af "adelay=150:all=1,apad,atrim=duration=${duration},aresample=48000,aformat=sample_fmts=s16:channel_layouts=stereo" \
    -c:a pcm_s16le "${segment_audio}"

  printf "file '%s'\n" "${segment_audio}" >>"${CONCAT_LIST}"
done

NARRATION_WAV="${AUDIO_TMP_DIR}/narration.wav"
ffmpeg -hide_banner -loglevel error \
  -f concat -safe 0 -i "${CONCAT_LIST}" \
  -af "loudnorm=I=-18:TP=-1.5:LRA=11" \
  -c:a pcm_s16le "${NARRATION_WAV}"

ffmpeg -hide_banner -loglevel error \
  -i "${NARRATION_WAV}" \
  -c:a aac -b:a 160k -ar 48000 \
  -metadata title="OpenAMRobot UI Feature Tour Narration" \
  -metadata artist="openAMRobot" \
  -movflags +faststart \
  -y "${OUTPUT_AUDIO}"

ffmpeg -hide_banner -loglevel error \
  -i "${SOURCE_VIDEO}" -i "${NARRATION_WAV}" \
  -map 0:v:0 -map 1:a:0 \
  -c:v copy -c:a aac -b:a 160k -ar 48000 -shortest \
  -metadata title="OpenAMRobot UI Feature Tour with Narration" \
  -metadata comment="Narration generated by scripts/create_narrated_video.sh" \
  -movflags +faststart \
  -y "${OUTPUT_VIDEO}"

echo "Created narration: ${OUTPUT_AUDIO}"
echo "Created narrated video: ${OUTPUT_VIDEO}"
ffprobe -v error \
  -show_entries format=duration,size:stream=codec_name,width,height,channels \
  -of default=noprint_wrappers=1 "${OUTPUT_VIDEO}"
